# Site
repository: ewelinasobora/ewelina_sobora_cv
favicon: images/favicon.ico

# Personal info
name: Ewelina Sobora
title: Ruby/Ruby on Rails Developer
email: e@e-dot.uk

# Social links
twitter_username: exwxexl
github_username:  ewelinasobora
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll

linkedin_username: ewelina-sobora
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ewelina and I specialize in Ruby and Ruby on Rails Development. My interest in logic and the process of bringing innovative ideas to fruition has been a lifelong passion. This journey began during my undergraduate studies, where I pursued a BSc in Mathematics and Economics, along with International Relations in my hometown in Poland. It was here that I was first introduced to the world of coding, and I was immediately drawn to its expressive and creative potential. After completing my degree, I embarked on a career as a Sales Representative in Cracow, gaining valuable insights into the business world. However, my passion for technology continued to grow and I made the bold decision to pursue my ambitions in London. Dedicated to the pursuit of continuous learning and skills development, I am committed to evolving my expertise in this field.
# Section
content:
  - title: Certificates # Title for the section
    layout: list
    content:
      - layout: top-middle
        title: AWS Certified Cloud Practitioner
        link: https://www.credly.com/badges/08a764b5-f81b-4b7e-9849-828e0498fdcc?source=linked_in_profile
# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

darkmode: true

plugins:
 - jekyll-seo-tag


exclude : ["Gemfile"]